bootcmd:
  - "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
apt:
  sources:
    hashicorp:
      source: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
package_update: true
packages:
  - consul
  - unzip
  - jq
write_files:
  - path: /etc/consul.d/consul.hcl
    owner: consul:consul
    encoding: b64
    defer: true
    content: |
      IyBkYXRhX2RpcgojIENvbmZpZ3VyZXMgdGhlIGRhdGEgZGlyZWN0b3J5IGZvciB0aGlzIGFnZW50CmRhdGFfZGlyID0gIi9vcHQvY29uc3VsIgoKIyBjb25uZWN0CiMgVGhpcyBzdGFuemEgY29uZmlndXJlcyBjb25uZWN0LCB0aGUgbmFtZQojIGZvciB0aGUgc2VydmljZSBtZXNoIGZlYXR1cmVzIG9mIENvbnN1bC4KY29ubmVjdCB7CiAgICAgIGVuYWJsZWQgPSB0cnVlCn0KCiMgcG9ydHMKIyBDb25maWd1cmVzIHdoaWNoIHBvcnRzIENvbnN1bCBsaXN0ZW5zIG9uLgojIFlvdSBuZWVkIHRvIGNvbmZpZ3VyZSBpdHMgZ1JQQyBwb3J0IHRvIGxpc3RlbiBvbiA4NTAyCiMgYmVjYXVzZSB0aGlzIGlzIHJlcXVpcmVkIGZvciB0aGUgc2VydmljZSBtZXNoIGZ1bmN0aW9uYWxpdHkuCnBvcnRzIHsKICAgICAgZ3JwYyA9IDg1MDIKfQoKIyBzZXJ2ZXIKIyBDb25maWd1cmVzIHRoaXMgYWdlbnQgdG8gcnVuIGFzIGEgc2VydmVyIChhcyBvcHBvc2VkIHRvIGEgY2xpZW50KS4Kc2VydmVyID0gdHJ1ZQoKIyBib290c3RyYXBfZXhwZWN0CiMgU2V0cyB0aGUgbnVtYmVyIG9mIHNlcnZlcnMgZXhwZWN0ZWQgdG8gYmUgaW4gdGhpcyBjbHVzdGVyLgojIFNpbmNlIHlvdSBvbmx5IGhhdmUgb25lIHNlcnZlciwgdGhpcyBpcyBzZXQgdG8gMS4KIyBUaGUgc2VydmVycyB3aWxsIHdhaXQgdW50aWwgdGhpcyBtYW55IHNlcnZlcnMKIyBoYXZlIGpvaW5lZCB0aGUgY2x1c3RlciBiZWZvcmUgdGhleSBzdGFydCB1cC4KYm9vdHN0cmFwX2V4cGVjdCA9IDEKCiMgdWlfY29uZmlnCiMgQ29uZmlndXJlcyBDb25zdWwncyBVSS4KIyBTZXQgZW5hYmxlZCB0byB0cnVlIHRvIGVuYWJsZSB0aGUgVUkuCnVpX2NvbmZpZyB7CiAgICAgIGVuYWJsZWQgPSB0cnVlCn0KCiMgY2xpZW50X2FkZHIKIyBUaGUgYWRkcmVzcyBDb25zdWwgYmluZHMgdG8gZm9yIGl0cyBIVFRQIEFQSS4KIyBUaGUgVUkgaXMgZXhwb3NlZCBvdmVyIHRoZSBIVFRQIEFQSSBzbyB0byBhY2Nlc3MKIyB0aGUgVUkgZnJvbSBvdXRzaWRlIHRoZSBWTSwgc2V0IHRoaXMgdG8gMC4wLjAuMCBzbyBpdAojIGJpbmRzIHRvIGFsbCBpbnRlcmZhY2VzLgpjbGllbnRfYWRkciA9ICIwLjAuMC4wIgoKIyBiaW5kX2FkZHIKIyBUaGUgYWRkcmVzcyBDb25zdWwgYmluZHMgdG8gZm9yIGludGVybmFsIGNsdXN0ZXIKIyBjb21tdW5pY2F0aW9uLiBVc3VhbGx5IHRoaXMgc2hvdWxkIGJlIHNldCB0bwojIDAuMC4wLjAgYnV0IGluIFZhZ3JhbnQsIHNldHRpbmcgdGhpcyB0byAxMjcuMC4wLjEKIyBwcmV2ZW50cyBpc3N1ZXMgaWYgdGhlIElQIGNoYW5nZXMuCmJpbmRfYWRkciA9ICIxMjcuMC4wLjEiCg==
      
  - path: /etc/systemd/system/frontend.service
    defer: true
    encoding: b64
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPSJGcm9udGVuZCBzZXJ2aWNlIgoKIyBUaGUgc2VydmljZSByZXF1aXJlcyB0aGUgVk0ncyBuZXR3b3JrCiMgdG8gYmUgY29uZmlndXJlZCwgZS5nLiwgYW4gSVAgYWRkcmVzcyBoYXMgYmVlbiBhc3NpZ25lZC4KUmVxdWlyZXM9bmV0d29yay1vbmxpbmUudGFyZ2V0CkFmdGVyPW5ldHdvcmstb25saW5lLnRhcmdldAoKW1NlcnZpY2VdCiMgRXhlY1N0YXJ0IGlzIHRoZSBjb21tYW5kIHRvIHJ1bi4KRXhlY1N0YXJ0PS91c3IvbG9jYWwvYmluL2Zyb250ZW5kCgojIFJlc3RhcnQgY29uZmlndXJlcyB0aGUgcmVzdGFydCBwb2xpY3kuIEluIHRoaXMgY2FzZSwgd2UKIyB3YW50IHRvIHJlc3RhcnQgdGhlIHNlcnZpY2UgaWYgaXQgZmFpbHMuClJlc3RhcnQ9b24tZmFpbHVyZQoKIyBFbnZpcm9ubWVudCBzZXRzIGVudmlyb25tZW50IHZhcmlhYmxlcy4KIyBXZSB3aWxsIHNldCB0aGUgZnJvbnRlbmQgc2VydmljZSB0byBsaXN0ZW4KIyBvbiBwb3J0IDYwNjAuCkVudmlyb25tZW50PUJJTkRfQUREUj0wLjAuMC4wOjYwNjAKCiMgV2Ugc2V0IEJBQ0tFTkRfVVJMIHRvIGh0dHA6Ly9sb2NhbGhvc3Q6NzAwMCBiZWNhdXNlCiMgdGhhdCdzIHRoZSBwb3J0IHdlJ2xsIHJ1biBvdXIgYmFja2VuZCBzZXJ2aWNlIG9uLgpFbnZpcm9ubWVudD1CQUNLRU5EX1VSTD1odHRwOi8vbG9jYWxob3N0OjcwMDAKCiMgVGhlIEluc3RhbGwgc2VjdGlvbiBjb25maWd1cmVzIHRoaXMgc2VydmljZSB0byBzdGFydAojIGF1dG9tYXRpY2FsbHkgaWYgdGhlIFZNIHJlYm9vdHMuCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo=

  - path: /etc/systemd/system/backend.service
    defer: true
    encoding: b64
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPSJCYWNrZW5kIHNlcnZpY2UiClJlcXVpcmVzPW5ldHdvcmstb25saW5lLnRhcmdldApBZnRlcj1uZXR3b3JrLW9ubGluZS50YXJnZXQKCltTZXJ2aWNlXQpFeGVjU3RhcnQ9L3Vzci9sb2NhbC9iaW4vYmFja2VuZApSZXN0YXJ0PW9uLWZhaWx1cmUKCiMgV2Ugd2lsbCBzZXQgdGhlIGJhY2tlbmQgc2VydmljZSB0byBsaXN0ZW4KIyBvbiBwb3J0IDcwMDAuCkVudmlyb25tZW50PUJJTkRfQUREUj0wLjAuMC4wOjcwMDAKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo=

  - path: /etc/systemd/system/frontend-sidecar-proxy.service
    defer: true
    encoding: b64
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPSJGcm9udGVuZCBzaWRlY2FyIHByb3h5IHNlcnZpY2UiClJlcXVpcmVzPW5ldHdvcmstb25saW5lLnRhcmdldApBZnRlcj1uZXR3b3JrLW9ubGluZS50YXJnZXQKCltTZXJ2aWNlXQpFeGVjU3RhcnQ9L3Vzci9iaW4vY29uc3VsIGNvbm5lY3QgZW52b3kgLXNpZGVjYXItZm9yIGZyb250ZW5kIFwKICAtYWRtaW4tYmluZCAxMjcuMC4wLjE6MTkwMDAKUmVzdGFydD1vbi1mYWlsdXJlCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQK

  - path: /etc/systemd/system/backend-sidecar-proxy.service
    defer: true
    encoding: b64
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPSJCYWNrZW5kIHNpZGVjYXIgcHJveHkgc2VydmljZSIKUmVxdWlyZXM9bmV0d29yay1vbmxpbmUudGFyZ2V0CkFmdGVyPW5ldHdvcmstb25saW5lLnRhcmdldAoKW1NlcnZpY2VdCkV4ZWNTdGFydD0vdXNyL2Jpbi9jb25zdWwgY29ubmVjdCBlbnZveSAtc2lkZWNhci1mb3IgYmFja2VuZCBcCiAgLWFkbWluLWJpbmQgMTI3LjAuMC4xOjE5MDAxClJlc3RhcnQ9b24tZmFpbHVyZQoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0Cg==

  - path: /etc/consul.d/frontend.hcl
    defer: true
    owner: consul:consul
    encoding: b64
    content: |
      c2VydmljZSB7CiAgbmFtZSA9ICJmcm9udGVuZCIKCiAgIyBmcm9udGVuZCBydW5zIG9uIHBvcnQgNjA2MC4KICBwb3J0ID0gNjA2MAoKICAjIFRoZSAiY29ubmVjdCIgc3RhbnphIGNvbmZpZ3VyZXMgc2VydmljZSBtZXNoCiAgIyBmZWF0dXJlcy4KICBjb25uZWN0IHsKICAgIHNpZGVjYXJfc2VydmljZSB7CiAgICAgICMgZnJvbnRlbmQncyBwcm94eSB3aWxsIGxpc3RlbiBvbiBwb3J0IDIxMDAwLgogICAgICBwb3J0ID0gMjEwMDAKCiAgICAgIHByb3h5IHsKICAgICAgICAjIFRoZSAidXBzdHJlYW1zIiBzdGFuemEgY29uZmlndXJlcwogICAgICAgICMgd2hpY2ggcG9ydHMgdGhlIHNpZGVjYXIgcHJveHkgd2lsbCBleHBvc2UKICAgICAgICAjIGFuZCB3aGF0IHNlcnZpY2VzIHRoZXknbGwgcm91dGUgdG8uCiAgICAgICAgdXBzdHJlYW1zID0gWwogICAgICAgICAgewogICAgICAgICAgICAjIEhlcmUgeW91J3JlIGNvbmZpZ3VyaW5nIHRoZSBzaWRlY2FyIHByb3h5IHRvCiAgICAgICAgICAgICMgcHJveHkgcG9ydCA2MDAxIHRvIHRoZSBiYWNrZW5kIHNlcnZpY2UuCiAgICAgICAgICAgIGRlc3RpbmF0aW9uX25hbWUgPSAiYmFja2VuZCIKICAgICAgICAgICAgbG9jYWxfYmluZF9wb3J0ICA9IDYwMDEKICAgICAgICAgIH0KICAgICAgICBdCiAgICAgIH0KICAgIH0KICB9Cn0K

  - path: /etc/consul.d/backend.hcl
    defer: true
    owner: consul:consul
    encoding: b64
    content: |
      c2VydmljZSB7CiAgbmFtZSA9ICJiYWNrZW5kIgogICMgYmFja2VuZCBydW5zIG9uIHBvcnQgNzAwMC4KICBwb3J0ID0gNzAwMAoKICBtZXRhIHsKICAgIHZlcnNpb24gPSAidjEiCiAgfQoKICAjIFRoZSBiYWNrZW5kIHNlcnZpY2UgZG9lc24ndCBjYWxsCiAgIyBhbnkgb3RoZXIgc2VydmljZXMgc28gaXQgZG9lc24ndAogICMgbmVlZCBhbiAidXBzdHJlYW1zIiBzdGFuemEuCiAgIwogICMgVGhlIGNvbm5lY3Qgc3RhbnphIGlzIHN0aWxsIHJlcXVpcmVkIHRvCiAgIyBpbmRpY2F0ZSB0aGF0IGl0IG5lZWRzIGEgc2lkZWNhciBwcm94eS4KICBjb25uZWN0IHsKICAgIHNpZGVjYXJfc2VydmljZSB7CiAgICAgICMgYmFja2VuZCdzIHByb3h5IHdpbGwgbGlzdGVuIG9uIHBvcnQgMjIwMDAuCiAgICAgIHBvcnQgPSAyMjAwMAogICAgfQogIH0KfQo=
  
runcmd:
  - wget "https://github.com/consul-up/birdwatcher/releases/download/v1.0.0/frontend-linux-amd64" -O "/usr/local/bin/frontend"
  - wget "https://github.com/consul-up/birdwatcher/releases/download/v1.0.0/backend-linux-amd64" -O "/usr/local/bin/backend"
  - curl -sLo- https://archive.tetratelabs.io/envoy/download/v1.22.2/envoy-v1.22.2-linux-amd64.tar.xz | tar --strip-components 2 -xJvf - -C /usr/local/bin/
  - chmod +x /usr/local/bin/frontend
  - chmod +x /usr/local/bin/backend

  - systemctl daemon-reload

  - systemctl enable consul.service

  - systemctl enable frontend.service
  - systemctl enable backend.service
  - systemctl enable frontend-sidecar-proxy
  - systemctl enable backend-sidecar-proxy

  - systemctl start consul.service
  - systemctl start frontend.service
  - systemctl start backend.service
  - systemctl start frontend-sidecar-proxy
  - systemctl start backend-sidecar-proxy
